# Change these first
owner: Cleverclip # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Cleverclip
    url: https://cleverclipstudios.com
  - name: Cleverclip Wordpress
    url: https://backend.cleverclipstudios.com/wp-admin/
  - name: TEST
    url: http://sgsadsaasd.hu/

status-website:
  baseUrl: /status
  logoUrl: https://avatars2.githubusercontent.com/u/60980904?s=200&v=4
  name: Cleverclip Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
